name: Build macOS x86-Executable

on:
  push:
    tags:
      - 'v*.*'  # Trigger only for versioned tags like v1.0.0

jobs:
  build:
    runs-on: macos-latest  # Specify macOS runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements file that includes PyInstaller

      # Step 4: Change to script directory and build executable with PyInstaller (onefile)
      - name: Build MacOS x86-executable with PyInstaller
        env:
          APP_VERSION: ${{ github.ref_name }}  # Pass the tag name as an environment variable
        run: |
          cd script
          pyinstaller --onefile --name DeskSaveApp --target-arch x86_64 --noconsole --add-data "file_types.json:." --additional-hooks-dir=hooks --clean main.py

      # Step 5: Archive the application directory into a zip file
      - name: Archive application into a zip file
        run: |
          cd script/dist
          zip -r DeskSaveApp-macOS-x86.zip DeskSaveApp.app  # Only archive the .app bundle

      # Step 6: Upload the zip archive as a release asset
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')  # Only run this on tags
        with:
          files: |
            script/dist/DeskSaveApp-macOS-x86.zip
