name: Build And Release

on:
  push:
    tags:
      - 'v*.*'   # Trigger only for versioned tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Specify macOS and Windows runners

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements file

      # Step 4: Change to script directory and build executable directory with PyInstaller
      - name: Change to script directory and Build executable directory with PyInstaller
        run: |
          cd script
          pyinstaller --name DeskSaveApp --add-data "file_types.json:." main.py

      # Step 5: Archive the application directory into a zip file
      - name: Archive application directory
        run: |
          cd dist
          if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
            zip -r DeskSaveApp-Windows.zip DeskSaveApp
          else
            zip -r DeskSaveApp-macOS.zip DeskSaveApp

      # Step 6: Upload the zip archives as release assets
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')  # Only run this on tags
        with:
          files: |
            script/dist/DeskSaveApp-*.zip
